### ISSUE TITLE
Invalid email address for message submission!

### ISSUE THREAD

**Issue by tehsu** [arnoldle/phplist-plugin-submitByMailPlugin#2]
Putting in a normal email, even testing a personal email keeps reporting the following error, Invalid email address for message submission!

**Comment by tehsu** [comment]
Only seeing this issue when submitting the info using Chrome. I used safari and the info went through fine.

**Comment by arnoldle** [comment]
Thanks for the tip. The latest Chrome version?

Arnold

**Comment by tehsu** [comment]
Yeah, the latest version.

**Comment by arnoldle** [comment]
Would you mind giving me the email address that failed using Chrome?
Every address I have tried so far with Chrome works fine.

Arnold

**Comment by tehsu** [comment]
I used list@snyde.net and its seeing this issue, maybe it is one of the plugins on chrome. I can further test it.

**Comment by arnoldle** [comment]
It’s not a plugin. I found the same problem using Chrome.

I’ll check it out.

Arnold

**Comment by tehsu** [comment]
Ok, thanks.

**Comment by arnoldle** [comment]
Hi, 

But anyway I am now trimming all the extraneous white space from the form entries. After doing this, the plugin works as well with Chrome as with Safari. It accepts list@snyde.net mailto:list@snyde.net .

You should copy the files sbmajax.php and generateScripts.php from my repository and use them to replace the corresponding files in your installation.

Thanks for reporting your issue.

Arnold

**Comment by tehsu** [comment]
Ok, thank you, I submitted another issue, the email that is sent does not capture the from address name, such as, itll send list@snyde.net as the from address but not add Snyde Mailing List as the name. I'm no expert, but I'm trying to figure out what to change to allow this to happen. Much appreciated.

**Comment by arnoldle** [comment]
I will have to think about that. But, as a work-around, you might consider using a prefix in the subject line to identify the mailing list. You could use the listNamePrefix plugin https://resources.phplist.com/plugins/listnameprefix or the subjectPrefix plugin https://resources.phplist.com/plugins/subjectprefix for that.

Arnold
