### ISSUE TITLE
mime type not allowed

### ISSUE THREAD

**Issue by dvdp** [arnoldle/phplist-plugin-submitByMailPlugin#5]
Hi,
Whenever I try to submit a message, I'm getting 'mime type not allowed'. I checked the mail and the content type is multipart/alternative which should be supported according to the plugin documentation.
Any idea what could be the problem / how to fix this ? TIA
Danny Van de Pol

Figured it out: all plugin settings where 'null' in the DB - I have no clue why. I'm also not seeing the plugin settings in the Config - Settings menu so I guess that is related.
I manually entered the settings in the DB and that made things working - at lease almost.
POP message is handeled and escrowed - when I submit it, I see that it is not assigned to any mailing lists so that's another problem.

br
Danny

**Comment by arnoldle** [comment]
Multipart/alternative is a permissible mime type. The problem must be with the mime type of the other parts of the message. What are those types?

Arnold

**Comment by dvdp** [comment]
Hi Arnold

Pls read my update(s)
Most is working now but not all

Danny

On 21 October 2015 18:30:01 CEST, arnoldle notifications@github.com wrote:

> Multipart/alternative is a permissible mime type. The problem must be
> with the mime type of the other parts of the message. What are those
> types?
> 
> Arnold
> 
> > On Oct 21, 2015, at 3:30 AM, dvdp notifications@github.com wrote:
> > 
> > Hi,
> > Whenever I try to submit a message, I'm getting 'mime type not
> > allowed'. I checked the mail and the content type is
> > multipart/alternative which should be supported according to the plugin
> > documentation.
> > Any idea what could be the problem / how to fix this ? TIA
> > Danny Van de Pol
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-149952773

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dvdp** [comment]
Arnold,

To summarize:
- I don't see the plugin settings in the phpList config menu (very odd - I checked the code: compared with another plugin and with the plugin development documentation - all by the book so it looks but alas no settings) - to get around I entered the settings directly in the config table
- I can submit a message by mail, when I click the confirmation url the message is submitted to the queue but there are not lists assigned to it (the list id in the escrowed messages table is correct though)
  (fabulous plugin imho - I no longer need to train people in using the phpList GUI - just connect a mail account to the appropriate list and make an admin account - makes things super simple for them)
  Danny

**Comment by dvdp** [comment]
Oops, wrong button -  accidentally closed it

**Comment by arnoldle** [comment]
Hi,

The confirmation message just identifies the message by subject. It is assumed that the writer/confirmer knows already which list he/she is addressing. The message cannot be queued with a list being specified for the message. In the SBM plugin, the list is determined by the email  address to which the message is sent. So if there is no error when the message is confirmed and queued, the message will go to the correct list.

You should see the plugin settings under the Phplist Settings menu. The plugin settings should appear near the bottom of the Category “General Settings.” I don’t think that there are settings in any other category. See the attached screen shot.

Arnold

**Comment by dvdp** [comment]
Hi Arnold

Some misunderstanding here I think - I know where the settings should be but they just aren't there. I took a look at the code and compared and couldn't find any reason why they are not showing up.

I did use the 'Configure a lsit for submission by email' menu and configured a list for submission by email and I created a cron job to process the pop mail. All that is working but when the message is queued, it is not assigned to any lists. I looked into the mysql tables when the message was escrowed and that table contains the right list Id so up to that point things are OK. When I click the submit URL in the confirmation mail, the message gets queued indeed but it's not assigned to any lists - so I get things narrowed down to that specific step.

I can provide you with some screenshots and/or a admin login to my phpList if you want.

Danny

**Comment by arnoldle** [comment]
Please do.
A.

**Comment by arnoldle** [comment]
Here is another thing to try.
1. Go to ‘Manage Plugins’ under the Config menu and then deactivate the plugin.
2. With whatever editor you are using to look at the MySQL tables, go to the table named '<Phplist prefix>_config’ . Look for the item in that table named “859026df996ecf9a7fb1c1f4dc5b189f” .
3. Go back to ‘Manage Plugins’ and activate the SubmitByMailPlugin.

This should cause my plugin to re-initialize itself, creating the settings, setting the defaults, and adding the plugin settings to the settings of  Phplist.

I hope this helps with your problem.

Arnold

**Comment by dvdp** [comment]
Sure worth trying - do you mean I should delete that record ? 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Vrijdag 23 oktober 2015 23:18:30 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Here is another thing to try. 
1. Go to ‘Manage Plugins’ under the Config menu and then deactivate the plugin. 
2. With whatever editor you are using to look at the MySQL tables, go to the table named '<Phplist prefix>_config’ . Look for the item in that table named “859026df996ecf9a7fb1c1f4dc5b189f” . 
3. Go back to ‘Manage Plugins’ and activate the SubmitByMailPlugin. 

This should cause my plugin to re-initialize itself, creating the settings, setting the defaults, and adding the plugin settings to the settings of Phplist. 

I hope this helps with your problem. 

Arnold

**Comment by arnoldle** [comment]
Yes!!

I forgot to type that sentence! :-(
A.

**Comment by dvdp** [comment]
Tried that - still no settings for the plugin :-( 
If you want to have a look 
www.sint-jozefekeren.be/phpList/admin 
user: Support 
passwd: S!teGr0und 

That's only for phpList - to take a look into the files / db you'll need 
control panel access to my shared hosting of course. 

TIA 
Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Vrijdag 23 oktober 2015 23:23:43 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Yes!! 

I forgot to type that sentence! :-( 
A.

**Comment by arnoldle** [comment]
Hi, 
I see that you’re using Phplist 3.2.1. In fact, I have not tested the plugin with this version. I had thought that the chances were good that it would work, but it seems that it doesn’t. That’s the only way that I can explain the disappearance of the settings.

So, I will need to update my plugin to work with the latest version of Phplist.

Sorry about that! I will try to get a new version out soon.

Thanks,
Arnold

**Comment by dvdp** [comment]
Thx Arnold, 
Really appreciate your effort to figure this out. 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Vrijdag 23 oktober 2015 23:59:33 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi, 
I see that you’re using Phplist 3.2.1. In fact, I have not tested the plugin with this version. I had thought that the chances were good that it would work, but it seems that it doesn’t. That’s the only way that I can explain the disappearance of the settings. 

So, I will need to update my plugin to work with the latest version of Phplist. 

Sorry about that! I will try to get a new version out soon. 

Thanks, 
Arnold

**Comment by arnoldle** [comment]
Hi,

Please delete lines 283 through 288 in submitByMailPlugin.php, that is, the following lines should be removed:

```
# Startup code, all other objects are constructed 
# Returns false when we do not have the prereqs, which means we cannot start
# Also returns false when not running off a secure connection
public function activate() {
    return true;
```

  }

I think that removal of those lines will fix the problem with the settings.

Please let me know what happens. Also please inform of whatever remaining problems you have.

If this works, I’ll put it into a new release.

Thank you,
Arnold

**Comment by dvdp** [comment]
Hi Arnold, 

Well - deleting those lines fixed the settings thing so one problem less. 
I'm now going to try to submit a message. 
Many thanks for your help 

Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Zaterdag 24 oktober 2015 21:13:19 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi, 

Please delete lines 283 through 288 in submitByMailPlugin.php, that is, the following lines should be removed: 

# Startup code, all other objects are constructed

# Returns false when we do not have the prereqs, which means we cannot start

# Also returns false when not running off a secure connection

public function activate() { 
return true; 
} 

I think that removal of those lines will fix the problem with the settings. 

Please let me know what happens. Also please inform of whatever remaining problems you have. 

If this works, I’ll put it into a new release. 

Thank you, 
Arnold

**Comment by dvdp** [comment]
Hi Arnold, 

Settings problem is fixed but after I acknowledge the escrowed message, it is submitted 
to the queue but not assigned to the list: 

As I mentioned before, the table gwb_submitByMailPlugin_escrow 
contains the right list id (= the id of the list for which I have enabled submit by mail) 
so that should be a fairly simple problem too I guess ... 

Danny 
----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Zaterdag 24 oktober 2015 21:13:19 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi, 

Please delete lines 283 through 288 in submitByMailPlugin.php, that is, the following lines should be removed: 

# Startup code, all other objects are constructed

# Returns false when we do not have the prereqs, which means we cannot start

# Also returns false when not running off a secure connection

public function activate() { 
return true; 
} 

I think that removal of those lines will fix the problem with the settings. 

Please let me know what happens. Also please inform of whatever remaining problems you have. 

If this works, I’ll put it into a new release. 

Thank you, 
Arnold

**Comment by arnoldle** [comment]
Great. If no further problems arise, I will put out a new release without those lines, maybe in a couple of days.

If any issue appears before then, please let me know.

Thanks,
Arnold

**Comment by arnoldle** [comment]
Oops,  I missed this. I will take a look at it.

Arnold

**Comment by dvdp** [comment]
Hi Arnold, 

I've been exploring the code -if Google has informed me correctly, 
a targetlist should be assigned to the messagedata object. I didn't 
find such an assignment (yet). 
Keep in mind I don't have a lot of experience with phpList plugins (and 
php - I have Pearl roots ;-) ) ... 

Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Zondag 25 oktober 2015 00:06:03 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Oops, I missed this. I will take a look at it. 

Arnold

**Comment by arnoldle** [comment]
Hi Danny,

I doubt that you are going to be able to find the problem by just looking at the plugin code; the plugin works well with Phplist 3.1. The problem must be related to a change in the way that plugins are handled in Phplist 3.2 — or else a change in some Phplist function that the plugin uses to accomplish its task.

You can help mere by checking something out. When the submitted message is confirmed and sent to the queue by the plugin, the specification of the target list is lost. Does the same thing happen when the list is configured to save confirmed messages as a draft instead of queueing them for distribution?

The answer to this question might reveal the code area where the problem exists.

Thanks,
Arnold

**Comment by dvdp** [comment]
Afaik yes, but  I need to check 
I'll try from my phone
Otherwise look after this evening (MET)

On 25 October 2015 00:06:03 CEST, arnoldle notifications@github.com wrote:

> Oops,  I missed this. I will take a look at it.
> 
> Arnold
> 
> > On Oct 24, 2015, at 3:30 PM, dvdp notifications@github.com wrote:
> > 
> > Hi Arnold, 
> > 
> > Settings problem is fixed but after I acknowledge the escrowed
> > message, it is submitted 
> > to the queue but not assigned to the list: 
> > 
> > As I mentioned before, the table gwb_submitByMailPlugin_escrow 
> > contains the right list id (= the id of the list for which I have
> > enabled submit by mail) 
> > so that should be a fairly simple problem too I guess ... 
> > 
> > Danny 
> > ----- Oorspronkelijk bericht -----
> > 
> > Van: "arnoldle" notifications@github.com 
> > Aan: "arnoldle/phplist-plugin-submitByMailPlugin"
> > phplist-plugin-submitByMailPlugin@noreply.github.com 
> > Cc: "dvdp" danny.vandepol@telenet.be 
> > Verzonden: Zaterdag 24 oktober 2015 21:13:19 
> > Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not
> > allowed (#5) 
> > 
> > Hi, 
> > 
> > Please delete lines 283 through 288 in submitByMailPlugin.php, that
> > is, the following lines should be removed: 
> > 
> > # Startup code, all other objects are constructed
> > 
> > # Returns false when we do not have the prereqs, which means we
> > 
> > cannot start 
> > 
> > # Also returns false when not running off a secure connection
> > 
> > public function activate() { 
> > return true; 
> > } 
> > 
> > I think that removal of those lines will fix the problem with the
> > settings. 
> > 
> > Please let me know what happens. Also please inform of whatever
> > remaining problems you have. 
> > 
> > If this works, I’ll put it into a new release. 
> > 
> > Thank you, 
> > Arnold 
> > 
> > — 
> > Reply to this email directly or view it on GitHub . 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-150848006.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-150854733

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dvdp** [comment]
Hi Arnold 

Confirmed - when submitted as a draft message, it says 

This campaign will be sent to subscribers, who are member of the following lists: 

None yet 
br 
Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Maandag 26 oktober 2015 16:13:48 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

I doubt that you are going to be able to find the problem by just looking at the plugin code; the plugin works well with Phplist 3.1. The problem must be related to a change in the way that plugins are handled in Phplist 3.2 — or else a change in some Phplist function that the plugin uses to accomplish its task. 

You can help mere by checking something out. When the submitted message is confirmed and sent to the queue by the plugin, the specification of the target list is lost. Does the same thing happen when the list is configured to save confirmed messages as a draft instead of queueing them for distribution? 

The answer to this question might reveal the code area where the problem exists. 

Thanks, 
Arnold

**Comment by dvdp** [comment]
Apparently, drafts are not assigned to any list either.
Hth
Danny

On 26 October 2015 16:13:48 CET, arnoldle notifications@github.com wrote:

> Hi Danny,
> 
> I doubt that you are going to be able to find the problem by just
> looking at the plugin code; the plugin works well with Phplist 3.1. The
> problem must be related to a change in the way that plugins are handled
> in Phplist 3.2 — or else a change in some Phplist function that the
> plugin uses to accomplish its task.
> 
> You can help mere by checking something out. When the submitted message
> is confirmed and sent to the queue by the plugin, the specification of
> the target list is lost. Does the same thing happen when the list is
> configured to save confirmed messages as a draft instead of queueing
> them for distribution?
> 
> The answer to this question might reveal the code area where the
> problem exists.
> 
> Thanks,
> Arnold
> 
> > On Oct 26, 2015, at 3:56 AM, dvdp notifications@github.com wrote:
> > 
> > Hi Arnold, 
> > 
> > I've been exploring the code -if Google has informed me correctly, 
> > a targetlist should be assigned to the messagedata object. I didn't 
> > find such an assignment (yet). 
> > Keep in mind I don't have a lot of experience with phpList plugins
> > (and 
> > php - I have Pearl roots ;-) ) ... 
> > 
> > Danny 
> > 
> > ----- Oorspronkelijk bericht -----
> > 
> > Van: "arnoldle" notifications@github.com 
> > Aan: "arnoldle/phplist-plugin-submitByMailPlugin"
> > phplist-plugin-submitByMailPlugin@noreply.github.com 
> > Cc: "dvdp" danny.vandepol@telenet.be 
> > Verzonden: Zondag 25 oktober 2015 00:06:03 
> > Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not
> > allowed (#5) 
> > 
> > Oops, I missed this. I will take a look at it. 
> > 
> > Arnold 
> > 
> > > On Oct 24, 2015, at 3:30 PM, dvdp notifications@github.com wrote:
> > > 
> > > Hi Arnold, 
> > > 
> > > Settings problem is fixed but after I acknowledge the escrowed
> > > message, it is submitted 
> > > to the queue but not assigned to the list: 
> > > 
> > > As I mentioned before, the table gwb_submitByMailPlugin_escrow 
> > > contains the right list id (= the id of the list for which I have
> > > enabled submit by mail) 
> > > so that should be a fairly simple problem too I guess ... 
> > > 
> > > Danny 
> > > ----- Oorspronkelijk bericht ----- 
> > > 
> > > Van: "arnoldle" notifications@github.com 
> > > Aan: "arnoldle/phplist-plugin-submitByMailPlugin"
> > > phplist-plugin-submitByMailPlugin@noreply.github.com 
> > > Cc: "dvdp" danny.vandepol@telenet.be 
> > > Verzonden: Zaterdag 24 oktober 2015 21:13:19 
> > > Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not
> > > allowed (#5) 
> > > 
> > > Hi, 
> > > 
> > > Please delete lines 283 through 288 in submitByMailPlugin.php, that
> > > is, the following lines should be removed: 
> > > 
> > > # Startup code, all other objects are constructed
> > > 
> > > # Returns false when we do not have the prereqs, which means we
> > > 
> > > cannot start 
> > > 
> > > # Also returns false when not running off a secure connection
> > > 
> > > public function activate() { 
> > > return true; 
> > > } 
> > > 
> > > I think that removal of those lines will fix the problem with the
> > > settings. 
> > > 
> > > Please let me know what happens. Also please inform of whatever
> > > remaining problems you have. 
> > > 
> > > If this works, I’ll put it into a new release. 
> > > 
> > > Thank you, 
> > > Arnold 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub . 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-150848006.
> > 
> > — 
> > Reply to this email directly or view it on GitHub . 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-151066240.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arnoldle/phplist-plugin-submitByMailPlugin/issues/5#issuecomment-151169404

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arnoldle** [comment]
Hi Danny,

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed.

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web  pages.

The latest version of the plugin is 1.0b2.12.

Enjoy!  And thanks for reporting this issue.

Arnold

**Comment by dvdp** [comment]
Hi Arnold, 

Confirmed - I just upgraded the plugin and ran a test - works like a charm. 
Many thanks for spending your time to fix this. 
A great plugin, imho, this should be a standard phplist feature ... 

Cheers 
Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by dvdp** [comment]
Hi again Arnold, 

Now that things are working great, I got a feature request for you :-) 
It would be nice to be able to assign multiple mailboxes to a list so that 
different people can use the same list with a different template for submitbymail. 

I'm maintaining a list for a school holding all the parents' email addresses. 
Sometimes the head of the school or the secretary wants to distribute a 
message to all the parents using the school template, sometimes the 
parents board wants to send a mail to all the parents with their own 
template. Right now I'm doing that with two different lists with the same 
members which is not the cleanest way. 
Note that this would require an extra field in the 'Configure a list for submission 
by email' menu defining the email address for the confirmation message 
(right now you are using the list owner email address). 

If you ever feel like adding some extra to your plugin, think about this one ... 

Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by arnoldle** [comment]
Thanks for the idea, Danny. That would appear to be doable. I will think about it for a further release.

I am glad to hear that everything seems to be working OK. You’ve been very helpful. Thanks again.

Arnold

**Comment by dvdp** [comment]
Hi again Arnold, 

Apparently, only the owner of a list can queue messages. 
Is that test in your plugin or is that imposed by the phpList core ? 
If it's in your plugin, an option to turn it off would be very usefull, 
that way, i can allow multiple people (all beging admin in phpList of course) 
allow to post messages to the same list. 

Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by dvdp** [comment]
Arnold, 

Ignore my question - solved by making that admin a superadmin. 
Which makes sense, if the person can submitbymail to any list, 
it 'is' in fact a superadmin. 

Danny 

----- Oorspronkelijk bericht -----

Van: "Danny Van de Pol" danny.vandepol@telenet.be 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" reply@reply.github.com 
Verzonden: Dinsdag 10 november 2015 16:04:55 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi again Arnold, 

Apparently, only the owner of a list can queue messages. 
Is that test in your plugin or is that imposed by the phpList core ? 
If it's in your plugin, an option to turn it off would be very usefull, 
that way, i can allow multiple people (all beging admin in phpList of course) 
allow to post messages to the same list. 

Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by arnoldle** [comment]
Hey, great, Danny! I was about to suggest exactly that.

Thanks,
Arnold

**Comment by dvdp** [comment]
BTW, if you ever decide to use language strings, I'll provide 
you with the dutch translations (not the word's largest language 
group of course ...) 

Cheers 
Danny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Dinsdag 10 november 2015 17:21:00 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hey, great, Danny! I was about to suggest exactly that. 

Thanks, 
Arnold

**Comment by arnoldle** [comment]
Thanks, Danny. But it might be a while…  :-)

Arnold

**Comment by dvdp** [comment]
Hi Arnold, 

Our phpList has been upgraded to 3.2.5 and since then, I have back the problem 
with no settings showing up under 'Config'. I'm still trying to figure out what the problem 
is but it looks a lot like the previous issue with UTF8 - maybe reverted ... 
If you can find a moment to check, that could be very helpful. 
TIA 

DAnny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by dvdp** [comment]
Some extra info: 
The menu items that are created under 'Config' (like 'Configure a list ...', 'Create scripts ...', ...) 
disappear each time the cron job for the POP collector runs - I also get thrown out and need 
to login again when that happens. 

----- Oorspronkelijk bericht -----

Van: "Danny Van de Pol" danny.vandepol@telenet.be 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" reply@reply.github.com 
Verzonden: Dinsdag 31 mei 2016 20:23:14 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Arnold, 

Our phpList has been upgraded to 3.2.5 and since then, I have back the problem 
with no settings showing up under 'Config'. I'm still trying to figure out what the problem 
is but it looks a lot like the previous issue with UTF8 - maybe reverted ... 
If you can find a moment to check, that could be very helpful. 
TIA 

DAnny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by dvdp** [comment]
Arnold, 

My apologies - I think I just had a rough day ... 
Settings are there - I must be getting blind - for some reason 
I was convinced they were down below - they are not. 

The only problem I was having was that the script to collect 
the messages got removed - could be related to the upgrade 
or some sysadmin that messed up things (me again maybe). 

Anyway, things are back to normal, sorry if I wasted some 
of you time. 

br 
Danny 

----- Oorspronkelijk bericht -----

Van: "Danny Van de Pol" danny.vandepol@telenet.be 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" reply@reply.github.com 
Verzonden: Dinsdag 31 mei 2016 20:39:24 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Some extra info: 
The menu items that are created under 'Config' (like 'Configure a list ...', 'Create scripts ...', ...) 
disappear each time the cron job for the POP collector runs - I also get thrown out and need 
to login again when that happens. 

----- Oorspronkelijk bericht -----

Van: "Danny Van de Pol" danny.vandepol@telenet.be 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" reply@reply.github.com 
Verzonden: Dinsdag 31 mei 2016 20:23:14 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Arnold, 

Our phpList has been upgraded to 3.2.5 and since then, I have back the problem 
with no settings showing up under 'Config'. I'm still trying to figure out what the problem 
is but it looks a lot like the previous issue with UTF8 - maybe reverted ... 
If you can find a moment to check, that could be very helpful. 
TIA 

DAnny 

----- Oorspronkelijk bericht -----

Van: "arnoldle" notifications@github.com 
Aan: "arnoldle/phplist-plugin-submitByMailPlugin" phplist-plugin-submitByMailPlugin@noreply.github.com 
Cc: "dvdp" danny.vandepol@telenet.be 
Verzonden: Woensdag 4 november 2015 21:48:45 
Onderwerp: Re: [phplist-plugin-submitByMailPlugin] mime type not allowed (#5) 

Hi Danny, 

This is to let you know that I have completed updating the Submit By Mail plugin. The settings problem is, of course, fixed. The problem with messages being queued without a list ID turned out to have to with the latest version of Phplist setting the database to UTF8 — apparently. Anyway, testing shows the issue to be fixed. 

While doing the debugging, I found that my javascripts no longer worked. This problem arose from the way that the latest version of Phplist handles the javascripts on a plugin’s web pages. 

The latest version of the plugin is 1.0b2.12. 

Enjoy! And thanks for reporting this issue. 

Arnold

**Comment by arnoldle** [comment]
Thanks for letting me know that the issue is resolved.

Arnold

**Comment by dvdp** [comment]
Hi, 

Any chance someone of the phplist developers could take over support 
for the SubmitByMail plugin ? The developer (Arnold - Cc) is no longer 
working on phplist and does no longer support this/his module. 

Imho, this plugin should be promoted to a default phplist feature: it makes 
submitting a campaign the most simple job in the world: just send a mail 
and (optionally) confirm with a single click. If you need to delegate campaign 
creation to someone for whom the GUI is too complicated, this plugin is a 
gift from heaven, so please consider making it a default feature and if not, 
please keep on supporting it ... 

Best regards 
Danny
